# Labeler Configuration
# Automatically apply labels to PRs based on modified files or branch names.
# For more info: https://github.com/actions/labeler

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - '*.md'

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**'
          - 'index.html'
          - 'postcss.config.js'
          - 'tailwind.config.js'
          - 'vite.config.js'

backend:
  - changed-files:
      - any-glob-to-any-file:
          - 'api/**'
          - 'server/**'
          - 'firestore.rules'
          - 'firebase.json'
          - '.firebaserc'

ci/cd:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'

gssoc26:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/ISSUE_TEMPLATE/*gssoc*'
  - branch:
      - '*gssoc*'
      - '*GSSoC*'
      - '*Gssoc*'
      - '*GSSOC*'

nsoc26:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/ISSUE_TEMPLATE/*nsoc*'
  - branch:
      - '*nsoc*'
      - '*NSoC*'
      - '*Nsoc*'
      - '*NSOC*'
