export const config = {
  runtime: 'edge',
}

export default async function handler(req: Request) {
  try {
    const url = new URL(req.url)
    const parts = url.pathname.split('/')
    const username = parts[parts.length - 1] || 'profile'

    // Construct og image url (will be generated by the Edge OG route)
    const origin = `${url.protocol}//${url.host}`
    const ogImage = `${origin}/api/og/profile/${encodeURIComponent(username)}?v=${Date.now()}`

    const title = `${username} — RankerHub`;
    const description = `View ${username}'s RankerHub profile, achievements, streaks and leaderboard rank.`;

    const html = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(title)}</title>
    <meta property="og:title" content="${escapeHtml(title)}" />
    <meta property="og:description" content="${escapeHtml(description)}" />
    <meta property="og:image" content="${ogImage}" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${escapeHtml(title)}" />
    <meta name="twitter:description" content="${escapeHtml(description)}" />
    <meta name="twitter:image" content="${ogImage}" />
    <meta http-equiv="refresh" content="0;url=/profile/${encodeURIComponent(username)}" />
  </head>
  <body>
    <p>Redirecting to profile...</p>
    <script>location.replace('/profile/${encodeURIComponent(username)}')</script>
  </body>
</html>`

    return new Response(html, {
      status: 200,
      headers: {
        'content-type': 'text/html; charset=utf-8',
        // Allow caching by CDN; invalidate by query param when profile updates
        'cache-control': 'public, max-age=0, s-maxage=3600, stale-while-revalidate=86400'
      }
    })
  } catch (e) {
    return new Response('Error', { status: 500 })
  }
}

function escapeHtml(s: string) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}
