name: "📚 Documentation Issue"
description: "Suggest improvements, fixes, or new additions to documentation"
title: "[Docs]: "
labels: ["documentation", "gssoc26", "NSoC'26", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us keep our documentation accurate and friendly!
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Explain what needs to be updated and the proposed changes."
      placeholder: "Describe the documentation changes/issues here..."
    validations:
      required: true
