name: "❓ Question or Support"
description: "Ask a question, troubleshoot an issue, or get support"
title: "[Question]: "
labels: ["help wanted", "gssoc26", "NSoC'26", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Need help? Please ask! Remember to search past issues and GitHub Discussions first.
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Ask your question clearly and provide context."
      placeholder: "Describe your question or issue here..."
    validations:
      required: true
